/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models


/**
 * 
 * @param accessToken 
 * @param expiresIn 
 * @param refreshExpiresIn 
 * @param refreshToken 
 * @param tokenType 
 * @param idToken 
 * @param notBeforePolicy 
 * @param sessionState 
 * @param scope 
 * @param error 
 * @param errorDescription 
 * @param errorUri 
 */
data class AccessTokenResponse (

    val accessToken: kotlin.String? = null,
    val expiresIn: kotlin.Long? = null,
    val refreshExpiresIn: kotlin.Long? = null,
    val refreshToken: kotlin.String? = null,
    val tokenType: kotlin.String? = null,
    val idToken: kotlin.String? = null,
    val notBeforePolicy: kotlin.Int? = null,
    val sessionState: kotlin.String? = null,
    val scope: kotlin.String? = null,
    val error: kotlin.String? = null,
    val errorDescription: kotlin.String? = null,
    val errorUri: kotlin.String? = null
) {
}