/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models

import com.squareup.moshi.Json


/**
 *
 * @param accessToken
 * @param expiresIn
 * @param refreshExpiresIn
 * @param refreshToken
 * @param tokenType
 * @param idToken
 * @param notBeforePolicy
 * @param sessionState
 * @param scope
 * @param error
 * @param errorDescription
 * @param errorUri
 */
data class AccessTokenResponse(
    @Json(name = "access_token")
    val accessToken: kotlin.String? = null,
    @Json(name = "expires_in")
    val expiresIn: kotlin.Long? = null,
    @Json(name = "refresh_expires_in")
    val refreshExpiresIn: kotlin.Long? = null,
    @Json(name = "refresh_token")
    val refreshToken: kotlin.String? = null,
    @Json(name = "token_type")
    val tokenType: kotlin.String? = null,
    @Json(name = "id_token")
    val idToken: kotlin.String? = null,
    @Json(name = "not-before-policy")
    val notBeforePolicy: kotlin.Int? = null,
    @Json(name = "session_state")
    val sessionState: kotlin.String? = null,
    @Json(name = "scope")
    val scope: kotlin.String? = null,
    @Json(name = "error")
    val error: kotlin.String? = null,
    @Json(name = "error_description")
    val errorDescription: kotlin.String? = null,
    @Json(name = "error_uri")
    val errorUri: kotlin.String? = null
)
