/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models


/**
 * 
 * @param id 
 * @param postId 
 * @param postTitle 
 * @param userId 
 * @param userUsername 
 * @param userFirstName 
 * @param userLastName 
 * @param postSellerId 
 * @param postSellerUsername 
 * @param offer 
 * @param publishDate 
 * @param offerStatus 
 * @param speditionSpeditionCode 
 */
data class OfferDto (

    val id: kotlin.Long? = null,
    val postId: kotlin.Long? = null,
    val postTitle: kotlin.String? = null,
    val userId: kotlin.Long? = null,
    val userUsername: kotlin.String? = null,
    val userFirstName: kotlin.String? = null,
    val userLastName: kotlin.String? = null,
    val postSellerId: kotlin.Long? = null,
    val postSellerUsername: kotlin.String? = null,
    val offer: kotlin.Long? = null,
    val publishDate: java.util.Date? = null,
    val offerStatus: OfferStatus? = null,
    val speditionSpeditionCode: kotlin.String? = null
) {
    /**
    * 
    * Values: PENDING,ACCEPTED,DENIED
    */
    enum class OfferStatus(val value: kotlin.String){
        PENDING("PENDING"),
        ACCEPTED("ACCEPTED"),
        DENIED("DENIED");
    }
}