/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models


/**
 * 
 * @param id 
 * @param title 
 * @param sellerId 
 * @param sellerUsername 
 * @param publishedDate 
 * @param startingPrice 
 * @param status 
 * @param postImage 
 */
data class PostDto (

    val id: kotlin.Long? = null,
    val title: kotlin.String? = null,
    val sellerId: kotlin.Long? = null,
    val sellerUsername: kotlin.String? = null,
    val publishedDate: java.time.LocalDateTime? = null,
    val startingPrice: kotlin.Long? = null,
    val status: Status? = null,
    val postImage: kotlin.String? = null
) {
    /**
    * 
    * Values: AVAILABLE,UNAVAILABLE,DELETED
    */
    enum class Status(val value: kotlin.String){
        AVAILABLE("AVAILABLE"),
        UNAVAILABLE("UNAVAILABLE"),
        DELETED("DELETED");
    }
}