/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models

import it.unical.demacs.enterprise.fintedapp.models.UserDto

/**
 * 
 * @param id 
 * @param seller 
 * @param title 
 * @param startingPrice 
 * @param postImage 
 * @param publishedDate 
 */
data class PostDto (

    val id: kotlin.Long? = null,
    val seller: UserDto? = null,
    val title: kotlin.String? = null,
    val startingPrice: kotlin.Long? = null,
    val postImage: kotlin.String? = null,
    val publishedDate: java.util.Date? = null
) {
}