/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models


/**
 * 
 * @param id 
 * @param authorId 
 * @param authorUsername 
 * @param targetId 
 * @param targetUsername 
 * @param publishDate 
 * @param content 
 */
data class ReviewDto (

    val id: kotlin.Long? = null,
    val authorId: kotlin.Long,
    val authorUsername: kotlin.String,
    val targetId: kotlin.Long,
    val targetUsername: kotlin.String? = null,
    val publishDate: java.time.LocalDateTime,
    val content: kotlin.String
) {
}