/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models


/**
 * 
 * @param id 
 * @param sellerUsername 
 * @param purchaserUsername 
 * @param purchaserAddressRoute 
 * @param purchaserAddressNumber 
 * @param purchaserAddressCity 
 * @param date 
 * @param speditionCode 
 */
data class SpeditionDto (

    val id: kotlin.Long? = null,
    val sellerUsername: kotlin.String? = null,
    val purchaserUsername: kotlin.String? = null,
    val purchaserAddressRoute: kotlin.String? = null,
    val purchaserAddressNumber: kotlin.String? = null,
    val purchaserAddressCity: kotlin.String? = null,
    val date: java.util.Date? = null,
    val speditionCode: kotlin.String? = null
) {
}