/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models

/**
 * 
 * @param id 
 * @param firstName 
 * @param lastName 
 * @param username 
 * @param registrationDate 
 * @param balance 
 * @param credentialsEmail 
 * @param addressRoute 
 * @param addressNumber 
 * @param addressCity 
 * @param publishedPosts 
 * @param receivedReviews 
 * @param publishedReviews 
 * @param publishedOffers 
 */

data class UserPersonalProfileDto (

    val id: kotlin.Long? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val username: kotlin.String? = null,
    val registrationDate: java.util.Date? = null,
    val balance: kotlin.Long? = null,
    val credentialsEmail: kotlin.String? = null,
    val addressRoute: kotlin.String? = null,
    val addressNumber: kotlin.String? = null,
    val addressCity: kotlin.String? = null,
    val publishedPosts: kotlin.Array<PostBasicInfoDto>? = null,
    val publishedOffers: kotlin.Array<OfferDto>? = null
) {
}