/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package it.unical.demacs.enterprise.fintedapp.models.security


/**
 *
 * @param accessToken
 * @param expiresIn
 * @param refreshExpiresIn
 * @param refreshToken
 * @param tokenType
 * @param idToken
 * @param notBeforePolicy
 * @param sessionState
 * @param scope
 * @param error
 * @param errorDescription
 * @param errorUri
 */
data class AccessTokenResponse(

    val access_token: String? = null,
    val expires_in: Int? = null,
    val refresh_expires_in: Int? = null,
    val refresh_token: String? = null,
    val token_type: String? = null,
    val id_token: String? = null,
    val `not-before-policy`: Int? = null,
    val session_state: String? = null,
    val scope: String? = null,
    val error: String? = null,
    val error_description: String? = null,
    val error_uri: String? = null
) {
}